name: CI

on:
  pull_request:
    types: [ labeled ]

jobs:
  build:
    if: ${{ github.event.label.name == 'updated-profile-release' }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.7
    - name: Run a one-line script
      run: echo Hello, world!
