name: 'Action - Auto Release Builder' 

on:
  pull_request:
    types: [ labeled ]

jobs:
  build:
    if: ${{ github.event.label.name == 'updated-profile-release' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.7
        with:
          sparse-checkout: |
            Microsoft.PowerShell_profile.ps1
          sparse-checkout-cone-mode: false
  
      
      - name: Check Directory Contents
        run: |
          pwd
          ls 

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.REPO_TOKEN }}
          file: $PWD/Microsoft.PowerShell_profile.ps1
          asset_name: mything
          tag: ${{ github.ref }}
          overwrite: true
          body: "This is my release text"
